# worker.py
import os
import sys
import shutil
import subprocess
import json
from pathlib import Path
from datetime import datetime

# Config via ENV
MACHINE_INDEX = int(os.environ.get("MACHINE_INDEX", "0"))
TOTAL_MACHINES = int(os.environ.get("TOTAL_MACHINES", "20"))
UPLOAD_TRANSFERS = 2

BASE_DIR = Path(".")
INPUTS_DIR = BASE_DIR / "Inputs"
DATASETS_DIR = BASE_DIR / "datasets"

now = datetime.now()
BATCH_FOLDER = BASE_DIR / f"Batch--{now.strftime('%Y-%m-%d')}--node{MACHINE_INDEX}"

def log(msg): print(f"[Node {MACHINE_INDEX:02d}] {msg}", flush=True)

def run_extraction():
    all_files = sorted(list(INPUTS_DIR.rglob("*.json")))
    skip_names = {"resume_state.json", "package.json", "package-lock.json"}
    all_files = [f for f in all_files if f.name not in skip_names]

    # Mathematical Sharding
    my_files = [f for i, f in enumerate(all_files) if i % TOTAL_MACHINES == MACHINE_INDEX]
    
    if not my_files:
        log("⚠️ No files assigned to this node.")
        return

    DATASETS_DIR.mkdir(exist_ok=True)
    BATCH_FOLDER.mkdir(exist_ok=True)

    log(f"📦 Copying {len(my_files)} files to datasets/...")
    for f in my_files:
        shutil.copy2(f, DATASETS_DIR / f.name)

    # 🚀 EXTRACTION BUG FIX: Delete unassigned JSONs from Inputs/
    log("🧹 Isolating node: Removing unassigned JSONs from Inputs/")
    for f in INPUTS_DIR.rglob("*.json"):
        if f.name not in skip_names:
            try: f.unlink()
            except: pass

    # Run Extraction
    env = os.environ.copy()
    env["OUTPUT_FOLDER"] = str(BATCH_FOLDER)
    env["INPUT_FOLDER"] = str(DATASETS_DIR)
    env["MAX_WORKERS"] = "30"

    log("🚀 Running extraction script...")
    res = subprocess.run([sys.executable, "tor-colab-data-caption-follower-extract.py"], env=env)
    if res.returncode != 0:
        sys.exit(1)

def upload_data():
    if not BATCH_FOLDER.exists(): return

    # Load session mapping generated by plan_session.py
    try:
        with open("session_mapping.json", "r") as f:
            mapping = json.load(f)
            my_accounts = mapping.get(str(MACHINE_INDEX), [])
    except:
        log("⚠️ No session_mapping.json found! Falling back to raw index.")
        my_accounts = [f"insta_acc_{MACHINE_INDEX}", f"insta_acc_{MACHINE_INDEX+20}"]

    if not my_accounts:
        log("❌ No accounts assigned to this node in mapping!")
        sys.exit(1)

    remote_name = BATCH_FOLDER.name
    local_path = str(BATCH_FOLDER)
    file_count = sum(1 for _ in BATCH_FOLDER.rglob("*") if _.is_file())
    
    final_acc = "NONE"
    status = "FAILED"

    # 🚀 SMART FALLBACK UPLOAD LOOP
    for acc in my_accounts:
        remote_dest = f"{acc}:Insta_Extracted/{remote_name}"
        log(f"☁️ Trying upload to {remote_dest}")
        
        cmd = ["rclone", "copy", local_path, remote_dest, "--transfers", str(UPLOAD_TRANSFERS), "--retries", "3", "--verbose"]
        res = subprocess.run(cmd)

        if res.returncode == 0:
            log(f"✅ SUCCESS: Uploaded to {acc}")
            final_acc = acc
            status = "SUCCESS"
            break
        else:
            log(f"⚠️ FAILED on {acc}. Trying fallback account...")

    # CREATE NODE REPORT FOR ARTIFACTS
    report = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "node": MACHINE_INDEX,
        "batch_folder": remote_name,
        "primary_assigned_acc": my_accounts[0] if my_accounts else "N/A",
        "final_uploaded_acc": final_acc,
        "status": status,
        "files_count": file_count
    }
    
    with open(f"NodeReport_{MACHINE_INDEX}.json", "w") as f:
        json.dump(report, f)

if __name__ == "__main__":
    mode = sys.argv[2] if len(sys.argv) > 2 else "upload"
    if "--mode" in sys.argv:
        idx = sys.argv.index("--mode")
        mode = sys.argv[idx+1]

    if mode == "extract": run_extraction()
    elif mode == "upload": upload_data()
